---
- hosts: all
  become_user: root
  become: yes
  tasks: 
  - name: Enviar Banner de bienvenida
    template: 
      src: files/issue 
      dest: /etc/issue
      owner: root
      group: root
      mode: 0644 
      backup: yes
